Refactor: family, comment 도메인 리팩토링 및 swagger 적용
familymoments/family-moments-BE pull request #125
Opened 2024-01-11 15:14 UTC by serak0310

### 무엇을 위한 PR인가요?(: 뒤 설명추가)

- [x] 신규 기능 추가 : family, comment 도메인 swagger 적용
- [ ] 버그 수정 :
- [x] 리펙토링 : Error Handler refactoring
- [ ] 문서 업데이트 :
- [ ] 기타 : 

### 작업 내역

- swagger 적용
- 기존 controller의 user validation 삭제

2024-01-14 05:43 UTC, zzo3ozz requested changes
수고하셨습니다~

2024-01-14 05:43 UTC, zzo3ozz commented on family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentController.java
> +            @AuthenticationPrincipal User user,
User를 그대로 쓰면 user와 관련하여 보안 이슈가 생길 가능성이 있는 요소들이 docs에 그대로 노출되어 
@Parameter(hidden = true) 어노테이션을 통해 내부 요소를 숨기기로 했습니다!

2024-01-15 12:16 UTC, serak0310 commented on family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentController.java
> +            @AuthenticationPrincipal User user,
감사합니다~ 해당 부분 수정해서 다시 PR 날릴게요!

2024-01-16 08:29 UTC, serak0310 commented on family-moments/src/main/java/com/spring/familymoments/domain/comment/CommentController.java
> +            @AuthenticationPrincipal User user,
말씀 주신 내용 반영해서 푸쉬해뒀습니다~

2024-01-16 13:04 UTC, sonshn approved these changes
모두 확인했습니다! 수고하셨습니다! 👍

2024-01-17 05:41 UTC, Hajin-Lee0406 reviewed
확인했습니다!!

2024-01-17 05:44 UTC, spacewalk00 approved these changes
확인했습니다 ! 👍 👍 😄

2024-01-17 23:26 UTC, zzo3ozz approved these changes

2024-01-19 08:11 UTC, merged