feat: 파일 업로드 용량 초과 에러 예외 처리
familymoments/family-moments-BE pull request #132
Opened 2024-01-29 16:40 UTC by Hajin-Lee0406

### 무엇을 위한 PR인가요?(: 뒤 설명추가)

- [x] 신규 기능 추가 : 파일 업로드 용량 초과 예외 처리 추가
- [ ] 버그 수정 :
- [ ] 리펙토링 :
- [ ] 문서 업데이트 :
- [ ] 기타 : 

### 변경사항 및 이유

- 찾아보니까 해당 에러도 일반적으로 예외처리를 하고 있어 추가했습니다.

### 작업 후 기대 동작(스크린샷)

- 파일 업로드 시, 용량이 클 때 발생하는 에러 예외 처리
![image](https://github.com/familymoments/family-moments-BE/assets/68217805/4f0b222a-1020-4750-bda5-2a8712b9d619)

2024-01-30 03:57 UTC, sonshn approved these changes
확인했습니다! 👍  혹시 예외처리 되는 용량이 어느 정도인지 알 수 있나요?

2024-01-30 07:35 UTC, spacewalk00 approved these changes
확인했습니다 ! 👍 👍

2024-01-30 11:58 UTC, zzo3ozz commented
> 확인했습니다! 👍 혹시 예외처리 되는 용량이 어느 정도인지 알 수 있나요? 이미지 파일이 사용되는 API에 적용하면 되나요?

진 대신 답해드리자면 현재 저희 서버에서는 50MB 사이즈 파일까지는 에러를 뱉지 않습니다. (applicatioy.yml의 servlet.multipart 항목 확인해보시면 됩니다~~)
진이 작업해주신 내용은 특정 API에 따로 에러 핸들러를 적용해야하는 것이 아니라 어느 API든지 `MaxUploadSizeExceededException` exception이 발생하면 자동으로 설정한 response를 반환해주는 것으로 이해하시면 됩니다!
따라서 관련 API에 따로 적용할 사항은 없을 듯 보이네요! 👍

2024-01-30 11:59 UTC, zzo3ozz approved these changes
수고 많으셨습니다! 👍

2024-02-01 05:05 UTC, sonshn requested changes
@zzo3ozz 

작년에 프로젝트 템플릿을 생성할 때 다른 곳에서 참고했던 부분인데, 그런 의미였군요! 나중에 영상 업로드 기능이 구현되면 이쪽도 조절해야 할 수도 있을 것 같아요 🚀

2024-02-01 05:05 UTC, sonshn approved these changes

2024-02-08 12:42 UTC, merged